name: listinha_backend
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  postgresql2: ^1.0.4
  redis: ^3.1.0
  result_dart: ^1.0.6
  shelf: ^1.4.1
  shelf_modular: ^2.1.0
  uno: ^1.1.1
  # path: ^1.8.0

dev_dependencies:
  flutterando_analysis: ^0.0.2
  mocktail: ^0.3.0
  test: ^1.21.0
